-- Wordle game: admin-curated answer pool. Seeded with a starter list so the
-- game works immediately after deploy; admins can add/remove from /admin/wordle.

CREATE TABLE IF NOT EXISTS "wordle_words" (
  "word" text PRIMARY KEY,
  "created_by" text REFERENCES "user"("id") ON DELETE SET NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW()
);
--> statement-breakpoint
INSERT INTO "wordle_words" ("word") VALUES
  ('ABOUT'), ('ABOVE'), ('ACTOR'), ('ACUTE'), ('ADMIT'), ('ADOPT'), ('ADULT'),
  ('AFTER'), ('AGAIN'), ('AGENT'), ('AGREE'), ('AHEAD'), ('ALARM'), ('ALBUM'),
  ('ALERT'), ('ALIEN'), ('ALIVE'), ('ALLOW'), ('ALONE'), ('ALONG'), ('ALTER'),
  ('AMONG'), ('ANGER'), ('ANGLE'), ('ANGRY'), ('APART'), ('APPLE'), ('APPLY'),
  ('ARENA'), ('ARGUE'), ('ARISE'), ('ASIDE'), ('ASSET'), ('AVOID'), ('AWARD'),
  ('AWARE'), ('BADLY'), ('BAKER'), ('BASIC'), ('BEACH'), ('BEGIN'), ('BELOW'),
  ('BENCH'), ('BIRTH'), ('BLACK'), ('BLAME'), ('BLIND'), ('BLOCK'), ('BLOOD'),
  ('BOARD'), ('BRAIN'), ('BRAND'), ('BREAD'), ('BREAK'), ('BRIEF'), ('BRING'),
  ('BROAD'), ('BROWN'), ('BUILD'), ('BUILT'), ('CABLE'), ('CARRY'), ('CATCH'),
  ('CAUSE'), ('CHAIR'), ('CHART'), ('CHASE'), ('CHEAP'), ('CHECK'), ('CHIEF'),
  ('CHILD'), ('CIVIL'), ('CLAIM'), ('CLASS'), ('CLEAN'), ('CLEAR'), ('CLOCK'),
  ('CLOSE'), ('COACH'), ('COAST'), ('COULD'), ('COUNT'), ('COURT'), ('COVER'),
  ('CRAFT'), ('CRASH'), ('CREAM'), ('CROSS'), ('CROWD'), ('CROWN'), ('CURVE'),
  ('CYCLE'), ('DAILY'), ('DANCE'), ('DEATH'), ('DELAY'), ('DEPTH'), ('DOUBT'),
  ('DOZEN'), ('DRAFT'), ('DRAMA'), ('DREAM'), ('DRESS'), ('DRILL'), ('DRINK'),
  ('DRIVE'), ('EARLY'), ('EARTH'), ('EIGHT'), ('ELITE'), ('EMPTY'), ('ENEMY'),
  ('ENJOY'), ('ENTER'), ('ENTRY'), ('EQUAL'), ('ERROR'), ('EVENT'), ('EVERY'),
  ('EXACT'), ('EXIST'), ('EXTRA'), ('FAITH'), ('FALSE'), ('FAULT'), ('FIELD'),
  ('FIFTH'), ('FIFTY'), ('FIGHT'), ('FINAL'), ('FIRST'), ('FLASH'), ('FLEET'),
  ('FLOOR'), ('FLUID'), ('FOCUS'), ('FORCE'), ('FORTH'), ('FORTY'), ('FOUND'),
  ('FRAME'), ('FRANK'), ('FRESH'), ('FRONT'), ('FRUIT'), ('FULLY'), ('FUNNY'),
  ('GIANT'), ('GIVEN'), ('GLASS'), ('GLOBE'), ('GRACE'), ('GRADE'), ('GRAND'),
  ('GRANT'), ('GRASS'), ('GREAT'), ('GREEN'), ('GROUP'), ('GROWN'), ('GUARD'),
  ('GUESS'), ('GUEST'), ('GUIDE'), ('HAPPY'), ('HEART'), ('HEAVY'), ('HORSE'),
  ('HOTEL'), ('HOUSE'), ('HUMAN'), ('IDEAL'), ('IMAGE'), ('INDEX'), ('INPUT'),
  ('ISSUE'), ('JOINT'), ('JUDGE'), ('KNOWN'), ('LABEL'), ('LARGE'), ('LASER'),
  ('LATER'), ('LAUGH'), ('LAYER'), ('LEARN'), ('LEAST'), ('LEAVE'), ('LEGAL'),
  ('LEVEL'), ('LIGHT'), ('LIMIT'), ('LOCAL'), ('LOGIC'), ('LOOSE'), ('LOWER'),
  ('LUCKY'), ('LUNCH'), ('MAGIC'), ('MAJOR'), ('MAKER'), ('MARCH'), ('MATCH'),
  ('MAYBE'), ('MAYOR'), ('MEDIA'), ('METAL'), ('MIGHT'), ('MINOR'), ('MIXED'),
  ('MODEL'), ('MONEY'), ('MONTH'), ('MORAL'), ('MOTOR'), ('MOUNT'), ('MOUSE'),
  ('MOUTH'), ('MOVIE'), ('MUSIC'), ('NEVER'), ('NIGHT'), ('NOISE'), ('NORTH'),
  ('NOVEL'), ('NURSE'), ('OCEAN'), ('OFFER'), ('OFTEN'), ('ORDER'), ('OTHER'),
  ('PAINT'), ('PANEL'), ('PAPER'), ('PARTY'), ('PEACE'), ('PHASE'), ('PHONE'),
  ('PHOTO'), ('PIECE'), ('PILOT'), ('PITCH'), ('PLACE'), ('PLANE'), ('PLANT'),
  ('PLATE'), ('POINT'), ('POUND'), ('POWER'), ('PRESS'), ('PRICE'), ('PRIDE'),
  ('PRIME'), ('PRINT'), ('PRIOR'), ('PRIZE'), ('PROOF'), ('PROUD'), ('PROVE'),
  ('QUEEN'), ('QUICK'), ('QUIET'), ('QUITE'), ('RADIO'), ('RAISE'), ('RANGE'),
  ('RAPID'), ('RATIO'), ('REACH'), ('READY'), ('REFER'), ('RIGHT'), ('RIVAL'),
  ('RIVER'), ('ROUGH'), ('ROUND'), ('ROUTE'), ('ROYAL'), ('RURAL'), ('SCALE'),
  ('SCENE'), ('SCOPE'), ('SCORE'), ('SENSE'), ('SERVE'), ('SEVEN'), ('SHALL'),
  ('SHAPE'), ('SHARE'), ('SHARP'), ('SHEET'), ('SHELF'), ('SHELL'), ('SHIFT'),
  ('SHIRT'), ('SHOCK'), ('SHOOT'), ('SHORT'), ('SIGHT'), ('SINCE'), ('SIXTH'),
  ('SIZED'), ('SKILL'), ('SLEEP'), ('SLIDE'), ('SMALL'), ('SMART'), ('SMILE'),
  ('SMOKE'), ('SOLID'), ('SOLVE'), ('SORRY'), ('SOUTH'), ('SPACE'), ('SPARE'),
  ('SPEAK'), ('SPEED'), ('SPEND'), ('SPENT'), ('SPLIT'), ('SPORT'), ('STAFF'),
  ('STAGE'), ('STAKE'), ('STAND'), ('START'), ('STATE'), ('STEAM'), ('STEEL'),
  ('STICK'), ('STILL'), ('STOCK'), ('STONE'), ('STORE'), ('STORM'), ('STORY'),
  ('STRIP'), ('STUDY'), ('STUFF'), ('STYLE'), ('SUGAR'), ('SUITE'), ('SUPER'),
  ('SWEET'), ('TABLE'), ('TASTE'), ('TEACH'), ('TEETH'), ('THANK'), ('THEFT'),
  ('THEIR'), ('THEME'), ('THERE'), ('THESE'), ('THICK'), ('THING'), ('THINK'),
  ('THIRD'), ('THOSE'), ('THREE'), ('THREW'), ('THROW'), ('TIGHT'), ('TITLE'),
  ('TODAY'), ('TOPIC'), ('TOTAL'), ('TOUCH'), ('TOUGH'), ('TOWER'), ('TRACK'),
  ('TRADE'), ('TRAIN'), ('TREAT'), ('TREND'), ('TRIAL'), ('TRULY'), ('TRUST'),
  ('TRUTH'), ('TWICE'), ('UNDER'), ('UNION'), ('UNITY'), ('UNTIL'), ('UPPER'),
  ('UPSET'), ('URBAN'), ('USAGE'), ('USUAL'), ('VALID'), ('VALUE'), ('VIDEO'),
  ('VIRUS'), ('VISIT'), ('VITAL'), ('VOCAL'), ('VOICE'), ('WASTE'), ('WATCH'),
  ('WATER'), ('WHEEL'), ('WHERE'), ('WHICH'), ('WHILE'), ('WHITE'), ('WHOLE'),
  ('WHOSE'), ('WOMAN'), ('WORLD'), ('WORRY'), ('WORSE'), ('WORTH'), ('WOULD'),
  ('WOUND'), ('WRITE'), ('WRONG'), ('WROTE'), ('YIELD'), ('YOUNG'), ('YOUTH')
ON CONFLICT DO NOTHING;
