/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as ApiV1TodayRouteImport } from './routes/api/v1/today'
import { Route as ApiV1ProgressionRouteImport } from './routes/api/v1/progression'
import { Route as ApiV1EventsRouteImport } from './routes/api/v1/events'
import { Route as ApiPushVapidPublicKeyRouteImport } from './routes/api/push/vapid-public-key'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedUHandleRouteImport } from './routes/_authenticated/u.$handle'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated/tasks/new'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks/$taskId'
import { Route as AuthenticatedSettingsMcpRouteImport } from './routes/_authenticated/settings/mcp'
import { Route as AuthenticatedSettingsHomeAssistantRouteImport } from './routes/_authenticated/settings/home-assistant'
import { Route as AuthenticatedSettingsApiDocsRouteImport } from './routes/_authenticated/settings/api-docs'
import { Route as ApiV1TasksIndexRouteImport } from './routes/api/v1/tasks/index'
import { Route as ApiV1TasksTaskIdRouteImport } from './routes/api/v1/tasks/$taskId'
import { Route as ApiV1InstancesInstanceIdSnoozeRouteImport } from './routes/api/v1/instances/$instanceId/snooze'
import { Route as ApiV1InstancesInstanceIdSkipRouteImport } from './routes/api/v1/instances/$instanceId/skip'
import { Route as ApiV1InstancesInstanceIdCompleteRouteImport } from './routes/api/v1/instances/$instanceId/complete'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1TodayRoute = ApiV1TodayRouteImport.update({
  id: '/api/v1/today',
  path: '/api/v1/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProgressionRoute = ApiV1ProgressionRouteImport.update({
  id: '/api/v1/progression',
  path: '/api/v1/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidPublicKeyRoute = ApiPushVapidPublicKeyRouteImport.update({
  id: '/api/push/vapid-public-key',
  path: '/api/push/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUHandleRoute = AuthenticatedUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMcpRoute =
  AuthenticatedSettingsMcpRouteImport.update({
    id: '/settings/mcp',
    path: '/settings/mcp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsHomeAssistantRoute =
  AuthenticatedSettingsHomeAssistantRouteImport.update({
    id: '/settings/home-assistant',
    path: '/settings/home-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiDocsRoute =
  AuthenticatedSettingsApiDocsRouteImport.update({
    id: '/settings/api-docs',
    path: '/settings/api-docs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1TasksIndexRoute = ApiV1TasksIndexRouteImport.update({
  id: '/api/v1/tasks/',
  path: '/api/v1/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TasksTaskIdRoute = ApiV1TasksTaskIdRouteImport.update({
  id: '/api/v1/tasks/$taskId',
  path: '/api/v1/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InstancesInstanceIdSnoozeRoute =
  ApiV1InstancesInstanceIdSnoozeRouteImport.update({
    id: '/api/v1/instances/$instanceId/snooze',
    path: '/api/v1/instances/$instanceId/snooze',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1InstancesInstanceIdSkipRoute =
  ApiV1InstancesInstanceIdSkipRouteImport.update({
    id: '/api/v1/instances/$instanceId/skip',
    path: '/api/v1/instances/$instanceId/skip',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1InstancesInstanceIdCompleteRoute =
  ApiV1InstancesInstanceIdCompleteRouteImport.update({
    id: '/api/v1/instances/$instanceId/complete',
    path: '/api/v1/instances/$instanceId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/settings/home-assistant': typeof AuthenticatedSettingsHomeAssistantRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/u/$handle': typeof AuthenticatedUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/progression': typeof ApiV1ProgressionRoute
  '/api/v1/today': typeof ApiV1TodayRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRoute
  '/api/v1/tasks/': typeof ApiV1TasksIndexRoute
  '/api/v1/instances/$instanceId/complete': typeof ApiV1InstancesInstanceIdCompleteRoute
  '/api/v1/instances/$instanceId/skip': typeof ApiV1InstancesInstanceIdSkipRoute
  '/api/v1/instances/$instanceId/snooze': typeof ApiV1InstancesInstanceIdSnoozeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/settings/home-assistant': typeof AuthenticatedSettingsHomeAssistantRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/u/$handle': typeof AuthenticatedUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/progression': typeof ApiV1ProgressionRoute
  '/api/v1/today': typeof ApiV1TodayRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRoute
  '/api/v1/tasks': typeof ApiV1TasksIndexRoute
  '/api/v1/instances/$instanceId/complete': typeof ApiV1InstancesInstanceIdCompleteRoute
  '/api/v1/instances/$instanceId/skip': typeof ApiV1InstancesInstanceIdSkipRoute
  '/api/v1/instances/$instanceId/snooze': typeof ApiV1InstancesInstanceIdSnoozeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/_authenticated/settings/home-assistant': typeof AuthenticatedSettingsHomeAssistantRoute
  '/_authenticated/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/u/$handle': typeof AuthenticatedUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/progression': typeof ApiV1ProgressionRoute
  '/api/v1/today': typeof ApiV1TodayRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRoute
  '/api/v1/tasks/': typeof ApiV1TasksIndexRoute
  '/api/v1/instances/$instanceId/complete': typeof ApiV1InstancesInstanceIdCompleteRoute
  '/api/v1/instances/$instanceId/skip': typeof ApiV1InstancesInstanceIdSkipRoute
  '/api/v1/instances/$instanceId/snooze': typeof ApiV1InstancesInstanceIdSnoozeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/history'
    | '/stats'
    | '/today'
    | '/api/mcp'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/settings/api-docs'
    | '/settings/home-assistant'
    | '/settings/mcp'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/push/subscribe'
    | '/api/push/vapid-public-key'
    | '/api/v1/events'
    | '/api/v1/progression'
    | '/api/v1/today'
    | '/settings/'
    | '/tasks/'
    | '/api/v1/tasks/$taskId'
    | '/api/v1/tasks/'
    | '/api/v1/instances/$instanceId/complete'
    | '/api/v1/instances/$instanceId/skip'
    | '/api/v1/instances/$instanceId/snooze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/history'
    | '/stats'
    | '/today'
    | '/api/mcp'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/settings/api-docs'
    | '/settings/home-assistant'
    | '/settings/mcp'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/push/subscribe'
    | '/api/push/vapid-public-key'
    | '/api/v1/events'
    | '/api/v1/progression'
    | '/api/v1/today'
    | '/settings'
    | '/tasks'
    | '/api/v1/tasks/$taskId'
    | '/api/v1/tasks'
    | '/api/v1/instances/$instanceId/complete'
    | '/api/v1/instances/$instanceId/skip'
    | '/api/v1/instances/$instanceId/snooze'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/friends'
    | '/_authenticated/history'
    | '/_authenticated/stats'
    | '/_authenticated/today'
    | '/api/mcp'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/_authenticated/settings/api-docs'
    | '/_authenticated/settings/home-assistant'
    | '/_authenticated/settings/mcp'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/new'
    | '/_authenticated/u/$handle'
    | '/api/auth/$'
    | '/api/push/subscribe'
    | '/api/push/vapid-public-key'
    | '/api/v1/events'
    | '/api/v1/progression'
    | '/api/v1/today'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/api/v1/tasks/$taskId'
    | '/api/v1/tasks/'
    | '/api/v1/instances/$instanceId/complete'
    | '/api/v1/instances/$instanceId/skip'
    | '/api/v1/instances/$instanceId/snooze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushVapidPublicKeyRoute: typeof ApiPushVapidPublicKeyRoute
  ApiV1EventsRoute: typeof ApiV1EventsRoute
  ApiV1ProgressionRoute: typeof ApiV1ProgressionRoute
  ApiV1TodayRoute: typeof ApiV1TodayRoute
  ApiV1TasksTaskIdRoute: typeof ApiV1TasksTaskIdRoute
  ApiV1TasksIndexRoute: typeof ApiV1TasksIndexRoute
  ApiV1InstancesInstanceIdCompleteRoute: typeof ApiV1InstancesInstanceIdCompleteRoute
  ApiV1InstancesInstanceIdSkipRoute: typeof ApiV1InstancesInstanceIdSkipRoute
  ApiV1InstancesInstanceIdSnoozeRoute: typeof ApiV1InstancesInstanceIdSnoozeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/today': {
      id: '/api/v1/today'
      path: '/api/v1/today'
      fullPath: '/api/v1/today'
      preLoaderRoute: typeof ApiV1TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/progression': {
      id: '/api/v1/progression'
      path: '/api/v1/progression'
      fullPath: '/api/v1/progression'
      preLoaderRoute: typeof ApiV1ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid-public-key': {
      id: '/api/push/vapid-public-key'
      path: '/api/push/vapid-public-key'
      fullPath: '/api/push/vapid-public-key'
      preLoaderRoute: typeof ApiPushVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$handle': {
      id: '/_authenticated/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AuthenticatedUHandleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mcp': {
      id: '/_authenticated/settings/mcp'
      path: '/settings/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AuthenticatedSettingsMcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/home-assistant': {
      id: '/_authenticated/settings/home-assistant'
      path: '/settings/home-assistant'
      fullPath: '/settings/home-assistant'
      preLoaderRoute: typeof AuthenticatedSettingsHomeAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-docs': {
      id: '/_authenticated/settings/api-docs'
      path: '/settings/api-docs'
      fullPath: '/settings/api-docs'
      preLoaderRoute: typeof AuthenticatedSettingsApiDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/tasks/': {
      id: '/api/v1/tasks/'
      path: '/api/v1/tasks'
      fullPath: '/api/v1/tasks/'
      preLoaderRoute: typeof ApiV1TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tasks/$taskId': {
      id: '/api/v1/tasks/$taskId'
      path: '/api/v1/tasks/$taskId'
      fullPath: '/api/v1/tasks/$taskId'
      preLoaderRoute: typeof ApiV1TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/instances/$instanceId/snooze': {
      id: '/api/v1/instances/$instanceId/snooze'
      path: '/api/v1/instances/$instanceId/snooze'
      fullPath: '/api/v1/instances/$instanceId/snooze'
      preLoaderRoute: typeof ApiV1InstancesInstanceIdSnoozeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/instances/$instanceId/skip': {
      id: '/api/v1/instances/$instanceId/skip'
      path: '/api/v1/instances/$instanceId/skip'
      fullPath: '/api/v1/instances/$instanceId/skip'
      preLoaderRoute: typeof ApiV1InstancesInstanceIdSkipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/instances/$instanceId/complete': {
      id: '/api/v1/instances/$instanceId/complete'
      path: '/api/v1/instances/$instanceId/complete'
      fullPath: '/api/v1/instances/$instanceId/complete'
      preLoaderRoute: typeof ApiV1InstancesInstanceIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedSettingsApiDocsRoute: typeof AuthenticatedSettingsApiDocsRoute
  AuthenticatedSettingsHomeAssistantRoute: typeof AuthenticatedSettingsHomeAssistantRoute
  AuthenticatedSettingsMcpRoute: typeof AuthenticatedSettingsMcpRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
  AuthenticatedUHandleRoute: typeof AuthenticatedUHandleRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedSettingsApiDocsRoute: AuthenticatedSettingsApiDocsRoute,
  AuthenticatedSettingsHomeAssistantRoute:
    AuthenticatedSettingsHomeAssistantRoute,
  AuthenticatedSettingsMcpRoute: AuthenticatedSettingsMcpRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
  AuthenticatedUHandleRoute: AuthenticatedUHandleRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushVapidPublicKeyRoute: ApiPushVapidPublicKeyRoute,
  ApiV1EventsRoute: ApiV1EventsRoute,
  ApiV1ProgressionRoute: ApiV1ProgressionRoute,
  ApiV1TodayRoute: ApiV1TodayRoute,
  ApiV1TasksTaskIdRoute: ApiV1TasksTaskIdRoute,
  ApiV1TasksIndexRoute: ApiV1TasksIndexRoute,
  ApiV1InstancesInstanceIdCompleteRoute: ApiV1InstancesInstanceIdCompleteRoute,
  ApiV1InstancesInstanceIdSkipRoute: ApiV1InstancesInstanceIdSkipRoute,
  ApiV1InstancesInstanceIdSnoozeRoute: ApiV1InstancesInstanceIdSnoozeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
